version: "3"

services:
  caddy:
    image: caddy
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${HOME}/.caddy:/data"
      - "./config/Caddyfile:/etc/caddy/Caddyfile"
      - "./www:/www"
    links:
      - v2ray
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: always
    volumes:
      - "./config/config.json:/etc/v2ray/config.json"
